---
- hosts: all
  tasks:
    - apt:
        update_cache: yes
        name: "{{ item }}"
      loop:
        - cmake
        - git
        - wget

    - name: Docker ppa key
      apt_key: 
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Docker ppa
      apt_repository: 
        repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable'

    - name: Docker
      apt:
        name: docker-ce

    - name: Posix users which can use docker
      user:
        name: ubuntu
        groups:
          - docker

    - name: gitlab key
      apt_key:
        url: https://packages.gitlab.com/runner/gitlab-runner/gpgkey
        state: present

    - name: gitlab ppa
      apt_repository: 
        repo: 'deb [arch=amd64] https://packages.gitlab.com/gitlab/gitlab-ce/ubuntu/ bionic main'


    - name: gitlab Community edition
      apt:
        name: gitlab-ce
