---
- hosts: all
  vars_prompt:
    - name: "gitlabci_token"
      prompt: "Gitlab-runner Token: "
  remote_user: ubuntu
  become: yes
  tasks:
    - apt:
        update_cache: yes
        name: "{{ item }}"
      loop:
        - cmake
        - git
        - wget

    - name: Docker ppa key
      apt_key: 
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable        

    - name: Docker
      apt:
        name: docker-ce

    - name: Posix users which can use docker
      user:
        name: "{{ ansible_user }}"
        groups:
          - docker

    - name: gitlab
      get_url:
        url: https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh
        dest: /tmp/gitlab_script.sh

    - name: install gitlab runner
      shell: bash /tmp/gitlab_script.sh

    - name: gitlab Community edition
      apt:
        name: gitlab-runner

    - name: Register runner to GitLab
      command: gitlab-runner register >
        --non-interactive
        --url "https://gitlab.com/"
        --registration-token '{{ gitlabci_token }}'
        --description "gitlab_runner for the NLeSC-JCER projects"
        --tag-list "docker,nlescjcer"
        --executor "docker"
        --docker-image alpine:3
